apiVersion: nuodbaas.nuodb.com/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: nuodbaas/v1alpha1/project
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    name: basic
    organization: org
    sla: dev
    tier: n0.nano
