// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProjectInitParameters struct {

	// defined labels attached to the resource that can be used for filtering
	// User-defined labels attached to the resource that can be used for filtering
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The SLA for the project. Cannot be updated once the project is created.
	// The SLA for the project. Cannot be updated once the project is created.
	SLA *string `json:"sla,omitempty" tf:"sla,omitempty"`

	// (String) The service tier for the project
	// The service tier for the project
	Tier *string `json:"tier,omitempty" tf:"tier,omitempty"`
}

type ProjectObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// defined labels attached to the resource that can be used for filtering
	// User-defined labels attached to the resource that can be used for filtering
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the project
	// The name of the project
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization that the project belongs to
	// The organization that the project belongs to
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) The SLA for the project. Cannot be updated once the project is created.
	// The SLA for the project. Cannot be updated once the project is created.
	SLA *string `json:"sla,omitempty" tf:"sla,omitempty"`

	// (String) The service tier for the project
	// The service tier for the project
	Tier *string `json:"tier,omitempty" tf:"tier,omitempty"`
}

type ProjectParameters struct {

	// defined labels attached to the resource that can be used for filtering
	// User-defined labels attached to the resource that can be used for filtering
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the project
	// The name of the project
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) The organization that the project belongs to
	// The organization that the project belongs to
	// +kubebuilder:validation:Required
	Organization *string `json:"organization" tf:"organization,omitempty"`

	// (String) The SLA for the project. Cannot be updated once the project is created.
	// The SLA for the project. Cannot be updated once the project is created.
	// +kubebuilder:validation:Optional
	SLA *string `json:"sla,omitempty" tf:"sla,omitempty"`

	// (String) The service tier for the project
	// The service tier for the project
	// +kubebuilder:validation:Optional
	Tier *string `json:"tier,omitempty" tf:"tier,omitempty"`
}

// ProjectSpec defines the desired state of Project
type ProjectSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectInitParameters `json:"initProvider,omitempty"`
}

// ProjectStatus defines the observed state of Project.
type ProjectStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Project is the Schema for the Projects API. Resource for managing NuoDB projects created using the DBaaS Control Plane
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nuodbaas}
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sla) || (has(self.initProvider) && has(self.initProvider.sla))",message="spec.forProvider.sla is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tier) || (has(self.initProvider) && has(self.initProvider.tier))",message="spec.forProvider.tier is a required parameter"
	Spec   ProjectSpec   `json:"spec"`
	Status ProjectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectList contains a list of Projects
type ProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Project `json:"items"`
}

// Repository type metadata.
var (
	Project_Kind             = "Project"
	Project_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Project_Kind}.String()
	Project_KindAPIVersion   = Project_Kind + "." + CRDGroupVersion.String()
	Project_GroupVersionKind = CRDGroupVersion.WithKind(Project_Kind)
)

func init() {
	SchemeBuilder.Register(&Project{}, &ProjectList{})
}
